/*
 * This file is generated by jOOQ.
 */
package com.prewave.tree.jooq.indexes


import com.prewave.tree.jooq.tables.Edge

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val EDGE_FROM_ID_IDX: Index = Internal.createIndex(DSL.name("edge_from_id_idx"), Edge.EDGE, arrayOf(Edge.EDGE.TO_ID), false)
val EDGE_PATH_IDX: Index = Internal.createIndex(DSL.name("edge_path_idx"), Edge.EDGE, arrayOf(Edge.EDGE.PATH), false)
