/*
 * This file is generated by jOOQ.
 */
package com.prewave.tree.jooq.tables.records


import com.prewave.tree.jooq.tables.Edge

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl
import org.jooq.postgres.extensions.types.Ltree


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class EdgeRecord private constructor() : UpdatableRecordImpl<EdgeRecord>(Edge.EDGE) {

    open var fromId: Int
        set(value): Unit = set(0, value)
        get(): Int = get(0) as Int

    open var toId: Int
        set(value): Unit = set(1, value)
        get(): Int = get(1) as Int

    open var path: Ltree?
        set(value): Unit = set(2, value)
        get(): Ltree? = get(2) as Ltree?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Int?, Int?> = super.key() as Record2<Int?, Int?>

    /**
     * Create a detached, initialised EdgeRecord
     */
    constructor(fromId: Int, toId: Int, path: Ltree? = null): this() {
        this.fromId = fromId
        this.toId = toId
        this.path = path
        resetChangedOnNotNull()
    }
}
